body:
  - type: dropdown
    attributes:
      name: first_lang
      label: "First Language"
      defaultValue: "English"
      options:
        - "English"
        - "Russian"
        - "Hungarian"
        - "Dutch"
        - "Greek"
        - "Danish"
        - "Hebrew"
        - "Spanish"
        - "Italian"
        - "Chinese"
        - "Arabic"
        - "Korean"
        - "German"
        - "Persian"
        - "Polish"
        - "Portuguese"
        - "Romanian"
        - "Slovak"
        - "Thai"
        - "Turkish"
        - "Ukrainian"
        - "French"
        - "Hindi"
        - "Czech"
        - "Swedish"
        - "Japanese"
  - type: dropdown
    attributes:
      name: second_lang
      label: "Second Language"
      defaultValue: "Russian"
      options:
        - "English"
        - "Russian"
        - "Hungarian"
        - "Dutch"
        - "Greek"
        - "Danish"
        - "Hebrew"
        - "Spanish"
        - "Italian"
        - "Chinese"
        - "Arabic"
        - "Korean"
        - "German"
        - "Persian"
        - "Polish"
        - "Portuguese"
        - "Romanian"
        - "Slovak"
        - "Thai"
        - "Turkish"
        - "Ukrainian"
        - "French"
        - "Hindi"
        - "Czech"
        - "Swedish"
        - "Japanese"